"""Replay a deterministic AI Waiter order flow without a Gemini API key.

The script exercises the same data contracts the product uses: menu metadata,
allergy-aware recommendations, cart state, and WhatsApp checkout payloads.
"""

from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def flatten_menu(menu: dict) -> list[dict]:
    items: list[dict] = []
    for category in menu.get("categories", []):
        for item in category.get("items", []):
            row = dict(item)
            row["category"] = category.get("name", "unknown")
            items.append(row)
    return items


def main() -> None:
    RESULTS.mkdir(exist_ok=True)
    menu = load_json(ROOT / "menu.json")
    config = load_json(ROOT / "restaurant_config.json")
    items = flatten_menu(menu)

    vegetarian = [item for item in items if "vegetarian" in item.get("tags", []) and item.get("available", True)]
    peanut_safe = [item for item in vegetarian if "peanuts" not in item.get("allergens", [])]
    selected = peanut_safe[:2]
    if not selected:
        raise SystemExit("sample menu did not contain two vegetarian peanut-safe items")

    cart = [
        {
            "item_id": selected[0]["id"],
            "name": selected[0]["name"],
            "price": selected[0]["price"],
            "quantity": 1,
            "notes": "medium spice, peanut allergy noted",
        },
        {
            "item_id": selected[1]["id"],
            "name": selected[1]["name"],
            "price": selected[1]["price"],
            "quantity": 2,
            "notes": "shareable side",
        },
    ]
    total = round(sum(item["price"] * item["quantity"] for item in cart), 2)
    lines = [f"New Order from {config['name']}", ""]
    currency = config.get("currency_symbol", "$")
    for item in cart:
        line = f"- {item['quantity']}x {item['name']} - {currency}{item['price'] * item['quantity']:.2f}"
        if item["notes"]:
            line += f" ({item['notes']})"
        lines.append(line)
    lines.extend(["", f"Total: {currency}{total:.2f}"])
    message = "\n".join(lines)
    phone = config["whatsapp_number"].replace("+", "").replace(" ", "").replace("-", "")

    conversation = [
        {
            "role": "guest",
            "message": "I am vegetarian and allergic to peanuts. What is safe and filling?",
        },
        {
            "role": "waiter",
            "message": f"I recommend {selected[0]['name']} and {selected[1]['name']}; both avoid peanuts in this sample menu.",
            "cards": [selected[0]["id"], selected[1]["id"]],
        },
        {"role": "guest", "message": f"Add one {selected[0]['name']} and two {selected[1]['name']}."},
        {"role": "waiter", "message": "Done. I added those to your cart and kept the allergy note attached."},
    ]

    (RESULTS / "sample_conversation.json").write_text(
        json.dumps(conversation, indent=2) + "\n", encoding="utf-8"
    )
    (RESULTS / "cart_state.json").write_text(json.dumps({"items": cart, "total": total}, indent=2) + "\n", encoding="utf-8")
    (RESULTS / "whatsapp_checkout.json").write_text(
        json.dumps(
            {
                "visitor_id": "demo-visitor-001",
                "message": message,
                "total": total,
                "whatsapp_link": f"https://wa.me/{phone}?text={quote(message)}",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (RESULTS / "run_summary.md").write_text(
        "\n".join(
            [
                "# AI Waiter Replay Artifacts",
                "",
                "Generated by `python examples/replay_order_flow.py`.",
                "",
                "- Conversation transcript: `results/sample_conversation.json`",
                "- Live cart state: `results/cart_state.json`",
                "- WhatsApp handoff payload: `results/whatsapp_checkout.json`",
                "",
                "This replay does not call Gemini. It validates the product data flow around the agent.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
